name: InfraDeploy CD (Manual Apply)

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Elige el environment"
        required: true
        type: choice
        options:
          - dev
          - staging
          - prod

permissions:
  contents: read

env:
  AWS_REGION: eu-north-1

concurrency:
  group: infradeploy-cd-${{ inputs.environment }}
  cancel-in-progress: false

jobs:
  apply:
    name: Terraform Apply (${{ inputs.environment }})
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.13.5

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Who am I (AWS)
        run: |
          set -euo pipefail
          aws sts get-caller-identity

      - name: Terraform init (reconfigure backend)
        run: |
          set -euo pipefail
          terraform -chdir=environments/${{ inputs.environment }} init -reconfigure

      - name: Terraform state sanity check
        run: |
          set -euo pipefail
          terraform -chdir=environments/${{ inputs.environment }} state list > state.txt
          head -n 50 state.txt
          grep -q "module.alb.aws_lb.this" state.txt

      - name: Terraform plan
        run: |
          set -euo pipefail
          terraform -chdir=environments/${{ inputs.environment }} plan -no-color -lock-timeout=10m

      - name: Terraform apply
        run: |
          set -euo pipefail
          terraform -chdir=environments/${{ inputs.environment }} apply -auto-approve -lock-timeout=10m

